<template>
  <div
    class="d-flex flex-column justify-center align-center w-100 h-100 ma-0 pa-0"
  >
    <v-btn
      to="/login"
      height="3.6rem"
      width="8rem"
      color="info"
      rounded="pill"
      class="mb-2"
      >登录</v-btn
    >
    <v-btn
      to="/register"
      height="3.8rem"
      width="8rem"
      color="info"
      rounded="pill"
      class="mb-2"
      >注册</v-btn
    >
    <v-btn
      to="/home"
      height="3.8rem"
      width="8rem"
      color="info"
      rounded="pill"
      class="mb-2"
      >首页</v-btn
    >
    <v-btn
      to="/1d65as1"
      height="3.8rem"
      width="8rem"
      color="info"
      rounded="pill"
      class="mb-2"
      >404</v-btn
    >
  </div>
</template>
