/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./components/common/Toast copy 2.vue')['default']
    AlertMsg: typeof import('./components/common/AlertMsg.vue')['default']
    AppFrame: typeof import('./components/containers/AppFrame.vue')['default']
    Avatar: typeof import('./components/common/Avatar.vue')['default']
    AvatarBtn: typeof import('./components/button/AvatarBtn.vue')['default']
    Captcha: typeof import('./components/common/Captcha.vue')['default']
    copy: typeof import('./components/button/SettingBtn copy.vue')['default']
    DataTable: typeof import('./components/project/DataTable.vue')['default']
    Demo: typeof import('./components/button/Demo.vue')['default']
    DemoBtn: typeof import('./components/button/DemoBtn.vue')['default']
    Drawer: typeof import('./components/common/Drawer.vue')['default']
    Footer: typeof import('./components/common/Footer.vue')['default']
    Frame: typeof import('./components/containers/Frame.vue')['default']
    HCaptcha: typeof import('./components/common/HCaptcha.vue')['default']
    Icon: typeof import('./components/common/Icon.vue')['default']
    KazeFrame: typeof import('./components/containers/KazeFrame.vue')['default']
    LangBtn: typeof import('./components/button/LangBtn.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    Loadingircular: typeof import('./components/common/Loadingircular.vue')['default']
    LoadingIrcular: typeof import('./components/common/LoadingIrcular.vue')['default']
    LoadingLinear: typeof import('./components/common/LoadingLinear.vue')['default']
    LoadingPlace: typeof import('./components/common/LoadingPlace.vue')['default']
    LoginOA2: typeof import('./components/containers/LoginOA2.vue')['default']
    MenuBottom: typeof import('./components/containers/MenuBottom.vue')['default']
    MenuLeft: typeof import('./components/containers/MenuLeft.vue')['default']
    MenuMobile: typeof import('./components/containers/MenuMobile.vue')['default']
    MenuPc: typeof import('./components/containers/MenuPc.vue')['default']
    MenuPC: typeof import('./components/containers/MenuPC.vue')['default']
    NavBar: typeof import('./components/common/NavBar.vue')['default']
    NavBottom: typeof import('./components/common/NavBottom.vue')['default']
    NavLogin: typeof import('./components/containers/NavLogin.vue')['default']
    NeiAppNav: typeof import('./components/common/NeiAppNav.vue')['default']
    PcFrame: typeof import('./components/containers/PcFrame.vue')['default']
    PopMsg: typeof import('./components/common/PopMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBtn: typeof import('./components/button/SearchBtn.vue')['default']
    Setting: typeof import('./components/containers/Setting.vue')['default']
    SettingBtn: typeof import('./components/button/SettingBtn.vue')['default']
    Sheet: typeof import('./components/common/Sheet.vue')['default']
    SideBar: typeof import('./components/common/SideBar.vue')['default']
    SpeedBtn: typeof import('./components/button/SpeedBtn.vue')['default']
    TestBtn: typeof import('./components/button/TestBtn.vue')['default']
    ThemeBtn: typeof import('./components/button/ThemeBtn.vue')['default']
    Toast: typeof import('./components/common/Toast.vue')['default']
    Toast2: typeof import('./components/common/Toast2.vue')['default']
  }
}
