/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/chat/': RouteRecordInfo<'/chat/', '/chat', Record<never, never>, Record<never, never>>,
    '/common/404/': RouteRecordInfo<'/common/404/', '/common/404', Record<never, never>, Record<never, never>>,
    '/forget/': RouteRecordInfo<'/forget/', '/forget', Record<never, never>, Record<never, never>>,
    '/friend/': RouteRecordInfo<'/friend/', '/friend', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/me/': RouteRecordInfo<'/me/', '/me', Record<never, never>, Record<never, never>>,
    '/me/profile/': RouteRecordInfo<'/me/profile/', '/me/profile', Record<never, never>, Record<never, never>>,
    '/me/setting/': RouteRecordInfo<'/me/setting/', '/me/setting', Record<never, never>, Record<never, never>>,
    '/plugin/': RouteRecordInfo<'/plugin/', '/plugin', Record<never, never>, Record<never, never>>,
    '/register/': RouteRecordInfo<'/register/', '/register', Record<never, never>, Record<never, never>>,
  }
}
